wordpress:
  depends_on:
    - db
  image: wordpress:latest
  restart: always
  ports:
    - "8000:80"
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: MyWordPressUser
    WORDPRESS_DB_PASSWORD: Pa$$5w0rD
    WORDPRESS_DB_NAME: MyWordPressDatabaseName
  volumes:
    - ./:/var/www/html
    - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini

