version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_mysql_user
      WORDPRESS_DB_PASSWORD: your_mysql_password
      WORDPRESS_DB_NAME: your_mysql_database
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 

volumes:
  db_data:
  wordpress_data:
